### ISSUE TITLE
[1.10.2]The client from me and my friends crashing

### ISSUE THREAD

**Issue by ValonInc** [Arcaratus/BloodArsenal#102]
The client from me and my friend crash
here a link to a zip with the crash reports
http://www.mediafire.com/file/2od5qqex5rpbq9n/crash-2017-07-26_21.23.48-client.zip
i played this modpack
https://minecraft.curseforge.com/projects/beyond-the-universe
sorry for my bad english.

**Comment by MysticFlowP** [comment]
Crash when Shift + Scrolling fast
https://pastebin.com/raw/VQq9655D

**Comment by ValonInc** [comment]
No at me it crashes after
Pick Up a Item(gas Tank from mekanism)
Complete a multi Block(Fusion Reactor from nuclearcraft)
Place a Block(vanilla MC furnace)
And at my Friends after He ignite a nuke(from ic2)

**Comment by AlexPlus117** [comment]
Yes, it is happening at me too...

**Comment by DV666** [comment]
Same for me ^^ Hope a quick fix for that :) 

`Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at arc.bloodarsenal.util.handler.ClientHandler.onMouseEvent(ClientHandler.java:30)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_379_ClientHandler_onMouseEvent_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:232)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2205)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1741)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by Arcaratus** [comment]
Should be fixed now.
