### ISSUE TITLE
Sigil of Augmented Holding causes a hard-crash to desktop.

### ISSUE THREAD

**Issue by Gregorsharpe** [Arcaratus/BloodArsenal#113]
Modpack - FTB Beyond 1.11.0 (MC 1.10.2)

Crafting a Sigil of Augmented Holding seems to only consume one additional chest rather than eight, and as soon as it enters the player's inventory they crash on a Null Pointer exception. Spawning the Sigil in creative mode has the same effect, and is reproducible in both MP and SSP worlds. 

```
Time: 10/14/17 1:34 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at arc.bloodarsenal.item.sigil.ItemSigilAugmentedHolding.getHighlightTip(ItemSigilAugmentedHolding.java:55)
	at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:629)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:170)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1381)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Arcaratus** [comment]
Hmm... I'll take a look. Might be a Forge update that I wasn't around for.

**Comment by Bimmr** [comment]
Was just about to post this error. But now I'll just comment so I'll be notified of updates.

**Comment by laurad2423** [comment]
Hey, Having the same issue. Was there ever a solution found?

**Comment by FuzzBallJack** [comment]
This issue is still a thing. Linked with this All the mods ticket
[https://github.com/AllTheMods/ATM-1/issues/112](url)

**Issue description**
Holding (Selected player inventory item) or hovering over the sigil of Augmented Holding from Blood Arsenal is crashing the game.

**Ways of reproducing**
- Start new creative world
- Spawn in Sigil of Augmented holding - Blood Arsenal
- Mouse Hover over Sigil of Augmented Holding
- Game client locks up and crashes

**Crash reported issue**
`
errorjava.lang.NullPointerException: Unexpected error at arc.bloodarsenal.item.sigil.ItemSigilAugmentedHolding.getHighlightTip(ItemSigilAugmentedHolding.java:55) at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:629) at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:170) at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
`

**Versions**
Blood Arsenal Version 1-10.2 - 2.1.0-22
Blood Magic: Alchemical Wizardry Version 1.10.2-2.1.11-80
All the mods Version 3.02
