### ISSUE TITLE
Player kicked by server when activating the Sigil of Divinity

### ISSUE THREAD

**Issue by LemADEC** [Arcaratus/BloodArsenal#133]
As of 1.12.2-2.1.0-24, activating the Sigil of Divinity crash on the server causing the player to disconnect:
```
[14:42:33] [Server thread/INFO] [betterchunkloader]: Loaded all online chunkloaders for Player: ghostrecon215
[14:42:33] [Server thread/INFO] [minecraft/DedicatedServer]: ghostrecon215 joined the game
[14:42:33] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /88.152.11.146:50452
net.minecraft.util.ReportedException: Ticking player
>       at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zin000(NetHandlerPlayServer.java:2048) ~[pa.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
>       at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
>       at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
>       at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
>       at WayofTime.bloodmagic.util.helper.NetworkHelper.getSoulNetwork(NetworkHelper.java:61) ~[NetworkHelper.class:1.12.2-2.3.1-99]
>       at WayofTime.bloodmagic.item.ItemSigilToggleable.onUpdate(ItemSigilToggleable.java:84) ~[ItemSigilToggleable.class:1.12.2-2.3.1-99]
>       at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
>       at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
>       at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
>       at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172) ~[vp.class:?]
>       at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
>       ... 10 more
[14:42:33] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: ghostrecon215 lost connection: Internal server error
```

**Comment by Arcaratus** [comment]
Was the sigil bound to the player?

**Comment by LemADEC** [comment]
The sigil has to be activated to trigger the issue, so I guess it's bound at that time.
