### ISSUE TITLE
Crash using 1.9.4-2.0.0-10

### ISSUE THREAD

**Issue by DreadBoy** [Arcaratus/BloodArsenal#60]
I'm getting error using 2.0.0-10 but 2.0.0-5 works. Crash detail is below.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.7.jar)
  LoadingPlugin (Quark-beta-29.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 04/08/16 23:28
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:589)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError
	at arc.bloodarsenal.item.sigil.ItemSigilAugmentedHolding.<init>(ItemSigilAugmentedHolding.java:17)
	at arc.bloodarsenal.registry.ModItems.init(ModItems.java:93)
	at arc.bloodarsenal.BloodArsenal.preInit(BloodArsenal.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 796927776 bytes (760 MB) / 1959264256 bytes (1868 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1987 Optifine OptiFine_1.9.4_HD_U_B6 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1987.jar) 
	UCH	Forge{12.17.0.1987} [Minecraft Forge] (forge-1.9.4-12.17.0.1987.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCH	JEI{3.6.8.225} [Just Enough Items] (jei_1.9.4-3.6.8.225.jar) 
	UCH	abyssalcraft{1.9.2.7} [AbyssalCraft] (AbyssalCraft-1.9.4-1.9.2.7.jar) 
	UCH	cxlibrary{1.1.0} [CXLibrary] (cxlibrary-1.1.0-1.9.4.jar) 
	UCH	advInv{1.1.0} [Advanced Inventory] (advInv-1.9.4-1.1.0.jar) 
	UCH	Aroma1997CoreHelper{1.1.0.3} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.0.3.jar) 
	UCH	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCH	bagginses{2.4.2d} [Bagginses] (Bagginses-1.9.4-2.5.3.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCH	BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar) 
	UCH	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCH	blockdrops{1.0.5} [Block Drops] (BlockDrops-1.9.4-1.0.5.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.9.4-2.0.0-40.jar) 
	UCH	BloodMagic{1.9.4-2.0.3-53} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.3-53.jar) 
	UCE	BloodArsenal{1.9.4-2.0.0-10} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-10.jar) 
	UCH	Botania{r1.8-313} [Botania] (Botania-unofficial.r1.8-313.jar) 
	UCH	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCH	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCH	chiselsandbits{10.18} [Chisels & Bits] (chiselsandbits-10.18.jar) 
	UCH	ChiselsBytes{0.4} [Chisels & Bytes] (ChiselsBytes-1.9.4-0.4.jar) 
	UCH	disenchanter{1.3} [Disenchanter] (disenchanter-[1.9.4]1.3.jar) 
	UCH	double_jump{1.0.0} [DoubleJump] (DoubleJump-1.9.4-1.0.0.jar) 
	UCH	DurabilityShow{3.1.1} [Durability Show] (Durability Show-1.9.4-3.1.1.jar) 
	UCH	enchiridion{3.1.6} [Enchiridion] (Enchiridion-1.9.4-3.1.6.jar) 
	UCH	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.1_1.9.4.jar) 
	UCH	forestry{5.0.24.0} [Forestry] (forestry_1.9.4-5.0.24.0.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre2.jar) 
	UCH	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre2.jar) 
	UCH	InventoryPets{1.4.8.1} [Inventory Pets] (inventorypets-1.9.4-1.4.8.1.jar) 
	UCH	journeymap{1.9.4-5.2.4} [JourneyMap] (journeymap-1.9.4-5.2.4-unlimited.jar) 
	UCH	jeresources{0.4.6.39} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.39.jar) 
	UCH	lteleporters{1.1.2} [Lemon's Simple Teleporters] (LemonsSimpleTeleporters-1.1.2-MC1.9.4.jar) 
	UCH	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCH	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCH	Morpheus{1.9.4-3.1.5} [Morpheus] (Morpheus-1.9.4-3.1.5.jar) 
	UCH	shetiphiancore{3.2.7} [ShetiPhian-Core] (shetiphiancore-1.9.4-3.2.7.jar) 
	UCH	multistorage{1.1.5} [Multi-Storage] (multistorage-1.9.4-1.1.5.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-9.jar) 
	UCH	planttech{1.6.0} [Planttech] (planttech-1.6.0 - 1.9.4.jar) 
	UCH	Quark{beta-29} [Quark] (Quark-beta-29.jar) 
	UCH	xreliquary{1.9.4-1.3.2.404} [Reliquary] (Reliquary-1.9.4-1.3.2.404.jar) 
	UCH	Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar) 
	UCH	roots{0.110} [Roots] (roots-1.9.4-0.110.0.jar) 
	UCH	shadowmc{3.3.10} [ShadowMC] (ShadowMC-1.9.4-3.3.10.jar) 
	UCH	SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
	UCH	StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
	UCH	watchfulchevsky{b6} [Trust Is Nice, But...] (TINB_1.9_b6.jar) 
	UCH	totemic{1.9.4-0.7.7} [Totemic] (Totemic-1.9.4-0.7.7.jar) 
	UCH	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.197.jar) 
	UCH	wawla{2.3.0.194} [What Are We Looking At] (Wawla-1.10.2-2.3.0.197.jar) 
	UCH	ZDoctorBB{1.1} [Blood Baubles] (ZDoctorBB-1.1.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  cubex2.cxlibrary.CoreModTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.7.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-beta-29.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.0.3.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon HD 7800 Series'
	OptiFine Version: OptiFine_1.9.4_HD_U_B6
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13431 Compatibility Profile Context 16.150.2211.0
	OpenGlRenderer: AMD Radeon HD 7800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
```

**Comment by TehNut** [comment]
Maybe try a non-outdated version like `2.0.1-11`?

**Comment by DreadBoy** [comment]
Sorry, I was not aware there's 11, it's not visible in Curse launcher. Will try.

**Comment by Arcaratus** [comment]
I think the issue is that your Blood Magic version is higher than what that Blood Arsenal version was built on. Updating Blood Arsenal should fix the issue
